# Generated by Django 3.2.7 on 2022-06-21 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='departament',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api_rest.departments'),
            preserve_default=False,
        ),
    ]
